
import { ChatMessage } from '../types';

export const sendMessageToLocalModel = async (
  messages: ChatMessage[],
  modelName: string = 'qwen3-4b'
): Promise<ChatMessage> => {
  try {
    
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const lastMessage = messages[messages.length - 1];
    
    return {
      id: Date.now().toString(),
      role: 'assistant',
      content: `This is a mock response from the local ${modelName} model. In the actual implementation, this would be generated by running the model locally on the device. The user said: "${lastMessage.content}"`,
      model: modelName,
      timestamp: Date.now()
    };
  } catch (error) {
    console.error('Error sending message to local model:', error);
    throw error;
  }
};

export const isModelDownloaded = async (modelName: string): Promise<boolean> => {
  return false;
};

export const downloadModel = async (
  modelName: string, 
  progressCallback?: (progress: number) => void
): Promise<boolean> => {
  
  for (let i = 0; i <= 100; i += 10) {
    if (progressCallback) {
      progressCallback(i);
    }
    await new Promise(resolve => setTimeout(resolve, 500));
  }
  
  return true;
};
